// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type DeadLetter struct {
	ID              uuid.UUID       `json:"id"`
	TenantID        uuid.UUID       `json:"tenant_id"`
	OriginalPayload json.RawMessage `json:"original_payload"`
	Error           sql.NullString  `json:"error"`
	CreatedAt       sql.NullTime    `json:"created_at"`
}

type Message struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type MessagesTenant1 struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
